version: "3.3"

services:

  wordpress: 
    image: wordpress
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - wordpress:/var/www/html
    networks:
      - vye2cloud
    deploy:
     placement:
      constraints:
       - node.role == manager
     resources:
      limits:
       memory: 1G
     labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wordpress.rule=Host(`wp.vye2cloud.com`)"
      - "traefik.http.routers.wordpress.entrypoints=web"
      - "traefik.http.services.wordpress.loadbalancer.server.port=80" # it seems you always need to give traefik a port so it 'notices' the service
      - "traefik.http.routers.wordpress-secured.rule=Host(`wp.vye2cloud.com`)"
      - "traefik.http.routers.wordpress-secured.entrypoints=web-secured"
      - "traefik.http.routers.wordpress-secured.tls.certresolver=mytlschallenge"
      - "traefik.http.routers.wordpress.middlewares=redirect@file"
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql
    networks:
      - vye2cloud
    deploy:
     placement:
      constraints:
       - node.role == manager
     resources:
      limits:
       memory: 1G
      
networks:
 vye2cloud:
  driver: overlay

  
volumes:
 wordpress:
   external: true
 db:
   external: true